# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
minimum_pre_commit_version: 2.17.0
default_stages: [commit]
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-added-large-files
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: check-merge-conflict

- repo: https://github.com/jorisroovers/gitlint
  rev: v0.17.0
  hooks:
  - id: gitlint
