#!/bin/bash
# Add the directory given as first argument in the svn repository creating
# a new project named after the directory
svn_repository_root="/home/nicolas/.svn_server"
svn_directory="$1"
if [ -d "$svn_directory" ]; then
  parent_dir=`dirname "$svn_directory"`
  cd "$parent_dir"
  parent_dir=`pwd`
  directory_name=`basename "$svn_directory"`
  # clean the directory name
  projectname=`echo $directory_name | tr ' ' '_'` # | tr 'è' 'e' | tr 'ê' 'e'`
  svn_repository="$svn_repository_root/$projectname"
else
  echo "$svn_directory doesn't exist"
  exit 1
fi

echo parent of dir : $parent_dir 

echo "---> svn repository $svn_repository"


if [ -d $svn_repository_root ]; then
  cd $svn_repository_root
  echo Create SVN Repository $svn_repository
  svnadmin create $svn_repository
else
  echo "home repository $svn_repository_root doesn't exist"
  exit 1
fi

cd "$parent_dir/$svn_directory"
echo "Importing source to Repository"
svn import -m "First import made by add2svn.sh" file://$svn_repository
cd $parent_dir
mv "$directory_name" "${directory_name}".bak
echo "Checkout"
echo svn co file://$svn_repository
svn co file://$svn_repository
