#!/bin/bash
if [ $# -ne 3 ]; then
  echo Usage $0 \"subject\" \"date\" \"file\"
  exit 1
fi
echo $#
IMAILER="/home/nicolas/Documents/src/scripts/imailer.py"
SMTP="smtp.orange.fr"
FROM="nico.vince@gmail.com"
TO="fred.gg@gmail.com"
SUBJECT="[Courrier] $1"
CONTENT="Arrivé le $2"
ATTACH="$3"
for i in $ATTACH; do
  TMP="$TMP -j $i "
done
ATTACH=$TMP
echo "ATTACH = $ATTACH"

echo $IMAILER -t "$SMTP" -e "$FROM" -s "$SUBJECT" -m "$CONTENT" -d "$TO" $ATTACH
$IMAILER -t "$SMTP" -e "$FROM" -s "$SUBJECT" -m "$CONTENT" -d "$TO" $ATTACH
