#!/bin/sh


file_echo(){
	echo $1 >> index.html
}

current_directory=`pwd | sed s/"\/.*\/"//`

test -f index.html && rm -f index.html # remove index.html if exists

# generation of the html file 
file_echo "<html>"
file_echo "<head>"
file_echo "<title>Index of $current_directory </title>"
file_echo "<style type=\"text/css\">"
file_echo "img { border: 0; padding: 0 2px; vertical-align: text-bottom; }"
file_echo "td  { font-family: monospace; padding: 2px 3px; text-align: right; vertical-align: bottom; white-space: pre; }"
file_echo "td:first-child { text-align: left; padding: 2px 10px 2px 3px; }"
file_echo "table { border: 0; }"
file_echo "a.symlink { font-style: italic; }"
file_echo "</style>"
file_echo "</head>"

file_echo "<body>"
file_echo "<h1>Index of $current_directory</h1>"
file_echo "<hr/>"
file_echo "<table>"
file_echo "<tr><td><a href=\"..\">Parent Directory</a></td></tr>"
for i in *; do
	if [ -d "$i" ]; then # folders
		modified_date=`ls -lhd "$i" | awk '{print $6}'`
		modified_hour=`ls -lhd "$i" | awk '{print $7}'`
		file_echo "<tr>"
		file_echo "<td><a href=\"$i\">$i/</a></td>"
		file_echo "<td></td>" # size
		file_echo "<td>$modified_date</td>"
		file_echo "<td>$modified_hour</td>"
		file_echo "</tr>"
	fi
done

for i in *; do
	if [ ! -d "$i" ]; then # regular files not hidden
		size=`ls -lh "$i" | awk '{print $5}'`
		modified_date=`ls -lh "$i" | awk '{print $6}'`
		modified_hour=`ls -lh "$i" | awk '{print $7}'`
		file_echo "<tr>"
		file_echo "<td><a href=\"$i\">$i</a></td>"
		file_echo "<td>$size</td>"
		file_echo "<td>$modified_date</td>"
		file_echo "<td>$modified_hour</td>"
		file_echo "</tr>"
	fi
done
file_echo "</table>"
file_echo "</body>"
file_echo "</html>"
# end of html file
