#!/bin/bash
# run cpreprocessor and sort the file to view diff between on header reference file
# and another generated by another tool.
f1=$1
f2=$2

f1_strip=$1.strip
f2_strip=$2.strip

f1_sort=$1.sort
f2_sort=$2.sort

# strip comments
stripcomments.sh $f1 > $f1_strip
stripcomments.sh $f2 > $f2_strip


# sort for easy diff
sort $f1_strip > $f1_sort
sort $f2_strip > $f2_sort

echo diff $f1_sort $f2_sort
echo vimdiff $f1_sort $f2_sort
