#!/bin/sh

if [ "$2" = "vf" ]; then
  SUB=sub_vf
else
  SUB=sub_vo
fi

RMVBFILE=`find . -name *$1*.rmvb`
SUBFILE=`find $SUB -name *$1*.srt`

echo mplayer "$RMVBFILE" -sub "$SUBFILE"
mplayer "$RMVBFILE" -sub "$SUBFILE"
