#!/bin/sh
TMP_FILE=/tmp/was_playing_${USER}
DCOP_AMAROK="dcop amarok"
DCOP_AMAROK_PLAYER="$DCOP_AMAROK player"
$DCOP_AMAROK > /dev/null 2>&1
AMAROK_RUNNING=$?

if [ $AMAROK_RUNNING -eq 0 ]; then
  IS_PLAYING=`$DCOP_AMAROK_PLAYER isPlaying`
  echo $IS_PLAYING
  if [ $IS_PLAYING = "true" ]; then
    $DCOP_AMAROK_PLAYER pause
    touch $TMP_FILE 
  fi
fi

