#!/bin/sh
TMP_FILE=/tmp/was_playing_${USER}
DCOP_AMAROK="dcop amarok"
DCOP_AMAROK_PLAYER="$DCOP_AMAROK player"
$DCOP_AMAROK > /dev/null 2>&1
AMAROK_RUNNING=$?

if [ $AMAROK_RUNNING -eq 0 ]; then
  if [ -f $TMP_FILE ]; then
    $DCOP_AMAROK_PLAYER playPause
    rm -f $TMP_FILE 
  fi
fi
