#!/bin/sh
# This script copy mail from windows partition if the files on the windows partition are more recent than those on Linux partition
# Just add files you want to update in the COPY_FILES variable
PATH_MAIL_WIN="/windows/Documents and Settings/Nicolas/Application Data/Thunderbird/Profiles/p9t9jemv.default/Mail/Local Folders"
#PATH_MAIL_WIN="/windows/Documents\ and\ Settings/Nicolas/Application\ Data/Thunderbird/Profiles/p9t9jemv.default/Mail/Local\ Folders/"
PATH_MAIL_LIN="/home/nicolas/.mozilla-thunderbird/mk220idr.default/Mail/Local Folders"
COPY_FILES="Compas Compas.msf Compas.sbd Inbox Inbox.msf Inbox.sbd kde_bugs kde_bugs.msf kde_bugs.sbd"


for i in $COPY_FILES; do
	if [ -d "$PATH_MAIL_WIN/$i" ]; then
		cp -ruvf "$PATH_MAIL_WIN/$i" "$PATH_MAIL_LIN"
	fi
	if [ -f "$PATH_MAIL_WIN/$i" ]; then
		cp -uvf "$PATH_MAIL_WIN/$i" "$PATH_MAIL_LIN"
	fi
	
done
#cp -uvf --no-preserve=mode,owner "/windows/Documents and Settings/Nicolas/Application Data/Thunderbird/Profiles/p9t9jemv.default/Mail/Local Folders/Compas" "/home/nicolas/.mozilla-thunderbird/mk220idr.default/Mail/Local Folders/"
#cp -uvf --no-preserve=mode,owner "/windows/Documents and Settings/Nicolas/Application Data/Thunderbird/Profiles/p9t9jemv.default/Mail/Local Folders/Compas.msf" "/home/nicolas/.mozilla-thunderbird/mk220idr.default/Mail/Local Folders/"
#cp -ruvf --no-preserve=mode,owner "/windows/Documents and Settings/Nicolas/Application Data/Thunderbird/Profiles/p9t9jemv.default/Mail/Local Folders/Compas.sbd" "/home/nicolas/.mozilla-thunderbird/mk220idr.default/Mail/Local Folders/"
#cp -uvf --no-preserve=mode,owner "/windows/Documents and Settings/Nicolas/Application Data/Thunderbird/Profiles/p9t9jemv.default/Mail/Local Folders/Inbox" "/home/nicolas/.mozilla-thunderbird/mk220idr.default/Mail/Local Folders/"
#cp -uvf --no-preserve=mode,owner "/windows/Documents and Settings/Nicolas/Application Data/Thunderbird/Profiles/p9t9jemv.default/Mail/Local Folders/Inbox.msf" "/home/nicolas/.mozilla-thunderbird/mk220idr.default/Mail/Local Folders/"
#cp -ruvf --no-preserve=mode,owner "/windows/Documents and Settings/Nicolas/Application Data/Thunderbird/Profiles/p9t9jemv.default/Mail/Local Folders/Inbox.sbd" "/home/nicolas/.mozilla-thunderbird/mk220idr.default/Mail/Local Folders/"
