#!/bin/bash
TODO=~/Documents/.todo/TODO
if [ -z $1 ]; then
  cat -n $TODO
else
  if [ "$1" = "mp3" ]; then
    echo `osdama` >> $TODO
    echo >> $TODO
  else
    echo "$*" >> $TODO
    echo >> $TODO
  fi
fi

