#!/bin/bash

if [ $# -eq 0 ] ; then
  echo "rien à extraire..."
elif [ -f $1 ]; then
  case $1 in
    *.tar.bz2)      tar -jxvf $1    ;;
    *.tar.gz)       tar -zxvf $1    ;;
    *.bz2)          bzip2 -d $1     ;;
    *.gz)           gunzip -d $1    ;;
    *.tar)          tar -xvf $1     ;;
    *.tgz)          tar -zxvf $1    ;;
    *.zip)          unzip $1        ;;
    *.Z)            uncompress $1   ;;
    *.rar)          unrar x $1      ;;
    *)              echo "format de compression non pris en charge" ;;
  esac
else
  echo "ce fichier n'existe pas..."
fi 



