#!/bin/bash
file_list1310=~/work/SQN1310/srcv/ss/tops/ss_top_mac_platform/file_list_parsed
file_list5110=/home/nvincent/work/SQN3110/srcv/tops/wimax_top/wimax_srcv/ss/tops/ss_mac_platform_fpga/file_list_parsed

files=" \
ASIC/srcv/common/sequans_library/clkchange_bit.v \
ASIC/srcv/common/platform/prio_shifter.v \
ASIC/srcv/common/platform/ext_ahb2ahb.v \
ASIC/srcv/common/platform/ext_ahb_icm.v \
ASIC/srcv/common/platform/ahb_mux.v \
ASIC/srcv/common/sequans_library/version_number.v \
ASIC/srcv/ss/platform/mii/ss_top_mii.v \
ASIC/srcv/common/sequans_library/version_number.v \
ASIC/srcv/common/sequans_library/common.v \
ASIC/srcv/ss/platform/sdio/simple_fifos/stfm.v \
ASIC/srcv/ss/platform/sdio/simple_fifos/srfm.v \
ASIC/srcv/common/sequans_library/rst_bypass.v \
ASIC/srcv/common/sequans_library/clkchange_bit.v \
ASIC/srcv/common/sequans_library/sync_fifo.v \
ASIC/srcv/common/sequans_library/countBlockAtMax.v \
ASIC/srcv/common/sequans_library/sync_fifo.v \
ASIC/srcv/common/sequans_library/regfile.v \
ASIC/srcv/common/mac/crc.v \
ASIC/srcv/common/sequans_library/fifoInterrupts.v \
ASIC/srcv/common/config_regs/cfgmii_defs.v \
ASIC/srcv/common/config_regs/cfgmii.v \
ASIC/srcv/common/platform/mii/receiver/mrai.v \
ASIC/srcv/common/platform/mii/receiver/el234p.v \
ASIC/srcv/common/platform/mii/receiver/mrfm.sv \
ASIC/srcv/common/platform/mii/transmitter/mtai.sv \
ASIC/srcv/common/platform/mii/transmitter/mtfm.sv \
ASIC/srcv/common/platform/mii/transmitter/el234u.v \
ASIC/srcv/common/platform/mii/mac110/mac110.v \
ASIC/srcv/common/platform/mii/mac110/mac/mac.v \
ASIC/srcv/common/platform/mii/mac110/mac/mac_tx.v \
ASIC/srcv/common/platform/mii/mac110/mac/mtx_crc.v \
ASIC/srcv/common/platform/mii/mac110/mac/ifg.v \
ASIC/srcv/common/platform/mii/mac110/mac/mac_rx.v \
ASIC/srcv/common/platform/mii/mac110/mac/mrx_crc.v \
ASIC/srcv/common/platform/mii/mac110/mac/mrx_rfifo.v \
ASIC/srcv/common/platform/mii/mac110/mac/mac_flc.v \
ASIC/srcv/common/platform/mii/mac110/mac/mac_flr.v \
ASIC/srcv/common/platform/mii/mac110/mac/mac_flt.v \
ASIC/srcv/common/platform/mii/mac110/mht/mht.v \
ASIC/srcv/common/platform/mii/mac110/mht/mht_tx.v \
ASIC/srcv/common/platform/mii/mac110/mht/mht_rx.v \
ASIC/srcv/common/platform/mii/mac110/mhtxf/mhtxf.v \
ASIC/srcv/common/platform/mii/mac110/mhtxf/mhtxf_rdptr.v \
ASIC/srcv/common/platform/mii/mac110/mhtxf/mhtxf_wrptr.v \
ASIC/srcv/common/platform/mii/mac110/mhtxf/mhtxf_mem.v \
ASIC/srcv/common/platform/mii/mac110/mhtxf/mhtxf_sync.v \
ASIC/srcv/common/platform/mii/mac110/mhtrf/mhtrf.v \
ASIC/srcv/common/platform/mii/mac110/mhtrf/mhtrf_rdptr.v \
ASIC/srcv/common/platform/mii/mac110/mhtrf/mhtrf_wrptr.v \
ASIC/srcv/common/platform/mii/mac110/mhtrf/mhtrf_mem.v \
ASIC/srcv/common/platform/mii/mac110/mhtrf/mhtrf_sync.v \
ASIC/srcv/common/platform/mii/mac110/ach/ach.v \
ASIC/srcv/common/platform/mii/mac110/mim/mim.v \
ASIC/srcv/common/platform/mii/mac110/mcs/mcs.v \
ASIC/srcv/common/platform/mii/mac110/mmc/mmc.v \
ASIC/srcv/common/platform/mii/mac110/lpbk/txrx_intf.v \
ASIC/srcv/common/platform/mii/mac110/lpbk/lpbk_fifo.v \
ASIC/srcv/ss/platform/sdio/sdioip/sd_cdcsampler.v \
ASIC/srcv/ss/platform/sdio/sdioip/sd_cdcctrl.v \
ASIC/srcv/ss/platform/sdio/sdioip/sd_cdcmeta.v \
ASIC/srcv/ss/platform/sdio/sdioip/sd_cmd_hst.v \
ASIC/srcv/ss/platform/sdio/sdioip/sd_cmd_sys.v \
ASIC/srcv/ss/platform/sdio/sdioip/sd_out.v \
ASIC/srcv/ss/platform/sdio/sdioip/sd_dat_hst.v \
ASIC/srcv/ss/platform/sdio/sdioip/sd_dat.v \
ASIC/srcv/ss/platform/sdio/sdioip/sd_dat_sys.v \
ASIC/srcv/ss/platform/sdio/sdioip/sd_apb.v \
ASIC/srcv/ss/platform/sdio/sdioip/sd_card_sm.v \
ASIC/srcv/ss/platform/sdio/sdioip/sd_hst.v \
ASIC/srcv/ss/platform/sdio/sdioip/sd_sys.v \
ASIC/srcv/ss/platform/sdio/sdioip/sd_dma.v \
ASIC/srcv/ss/platform/sdio/sdioip/sdio_biu.v \
ASIC/srcv/ss/platform/sdio/sdioip/sdio.v \
ASIC/srcv/common/platform/ahb_beat_limiter.v \
ASIC/srcv/common/platform/ahb_mux.v \
ASIC/srcv/common/config_regs/cfgsdioip_regfile_defs.v \
ASIC/srcv/common/config_regs/cfgsdioip_regfile.v \
ASIC/srcv/common/platform/ahb_mem.v \
ASIC/srcv/common/config_regs/sdio_cccr_sdio_defs.v \
ASIC/srcv/common/config_regs/sdio_cccr_sdio.v \
ASIC/srcv/common/config_regs/sdio_cccr_soc_defs.v \
ASIC/srcv/common/config_regs/sdio_cccr_soc.v \
ASIC/srcv/ss/platform/sdio/cccr_wrapper.v \
ASIC/srcv/common/config_regs/sdio_fbr1_sdio_defs.v \
ASIC/srcv/common/config_regs/sdio_fbr1_sdio.v \
ASIC/srcv/common/config_regs/sdio_fbr1_soc_defs.v \
ASIC/srcv/common/config_regs/sdio_fbr1_soc.v \
ASIC/srcv/ss/platform/sdio/fbr1_wrapper.v \
ASIC/srcv/common/config_regs/sdio_cis_sdio_defs.v \
ASIC/srcv/common/config_regs/sdio_cis_sdio.v \
ASIC/srcv/common/config_regs/sdio_cis_soc_defs.v \
ASIC/srcv/common/config_regs/sdio_cis_soc.v \
ASIC/srcv/ss/platform/sdio/cis_wrapper.v \
ASIC/srcv/ss/platform/sdio/fifo_calc_used.v \
ASIC/srcv/ss/platform/sdio/fifoSimpleInterrupts_wr.v \
ASIC/srcv/ss/platform/sdio/fifoSimpleInterrupts_rd.v \
ASIC/srcv/common/config_regs/cfgsdio_sdio_defs.v \
ASIC/srcv/common/config_regs/cfgsdio_sdio.v \
ASIC/srcv/ss/platform/sdio/cfgsdio_sdio_wrapper.v \
ASIC/srcv/common/config_regs/cfgsdio_soc_defs.v \
ASIC/srcv/common/config_regs/cfgsdio_soc.v \
ASIC/srcv/ss/platform/sdio/sdio_configregs.v \
ASIC/srcv/ss/platform/sdio/sdio_ctrl.v \
ASIC/srcv/ss/platform/sdio/sdio2miirx/ahbS2WriteFifo.v \
ASIC/srcv/common/sequans_library/sync_fifo.v \
ASIC/srcv/ss/platform/sdio/sdio2miirx/sdio2miirx_ctrl.v \
ASIC/srcv/ss/platform/sdio/sdio2miirx/sdio2miirx.v \
ASIC/srcv/common/sequans_library/sync_fifo.v \
ASIC/srcv/ss/platform/sdio/miitx2sdio/fifo2ahb.v \
ASIC/srcv/ss/platform/sdio/miitx2sdio/miitx2sdio.v \
ASIC/srcv/ss/platform/sdio/simple_fifos/ahbS2WriteFifo2Fifos.v \
ASIC/srcv/ss/platform/sdio/simple_fifos/sdio2srfm_ctrl.v \
ASIC/srcv/common/sequans_library/sync_fifo.v \
ASIC/srcv/ss/platform/sdio/simple_fifos/srfm.v \
ASIC/srcv/ss/platform/sdio/simple_fifos/stfm.v \
ASIC/srcv/common/sequans_library/sync_fifo.v \
ASIC/srcv/ss/platform/sdio/miitx2sdio/fifo2ahb.v \
ASIC/srcv/ss/platform/sdio/miitx2sdio/miitx2sdio.v \
ASIC/srcv/ss/platform/sdio/simple_fifos/simple_fifos.v \
ASIC/srcv/ss/platform/sdio/top_sdio.v \
ASIC/srcv/common/platform/prio_shifter.v \
ASIC/srcv/common/platform/ext_ahb_icm.v \
ASIC/srcv/common/sequans_library/common.v \
ASIC/srcv/common/sequans_library/regfile.v \
ASIC/srcv/common/sequans_library/sync_fifo.v \
ASIC/srcv/common/platform/ahbMstr/rd_dphase.v \
ASIC/srcv/common/platform/ahbMstr/wr_dphase.v \
ASIC/srcv/common/platform/ahbMstr/mmpi.v \
ASIC/srcv/common/platform/ahbMstr/ahbMstr2Fifo.v \
ASIC/srcv/common/platform/ahbMstr/ahbMstrSyncRdWr.v \
ASIC/srcv/common/sequans_library/common.v \
ASIC/srcv/common/sequans_library/regfile.v \
ASIC/srcv/common/sequans_library/sync_fifo.v \
ASIC/srcv/common/sequans_library/mux_1hot.v \
ASIC/srcv/common/sequans_library/mux_1hot_dflt.v \
ASIC/srcv/common/platform/marbiter/marbiter.v \
ASIC/srcv/common/platform/prio_shifter.v \
ASIC/srcv/common/config_regs/signals_host_defs.v \
ASIC/srcv/common/config_regs/signals_host.v \
ASIC/srcv/common/config_regs/signals_soc_defs.v \
ASIC/srcv/common/config_regs/signals_soc.v \
ASIC/srcv/ss/platform/host_if/signals_wrapper.v \
ASIC/srcv/common/platform/ahb_mem.v \
ASIC/srcv/common/config_regs/base_addresses_defs.v \
ASIC/srcv/ss/platform/host_if/host_if.v \
ASIC/srcv/common/sequans_library/common.v \
ASIC/srcv/common/sequans_library/clkchange_bit.v \
ASIC/srcv/common/sequans_library/SQN_LOCAL_GC.v \
ASIC/srcv/common/config_regs/apbIf_uart_defs.v \
ASIC/srcv/common/config_regs/apbIf_uart.v \
ASIC/srcv/ss/platform/uart/uart_rx_ctrl.v \
ASIC/srcv/ss/platform/uart/uart_tx_ctrl.v \
ASIC/srcv/ss/platform/uart/uart_tx_fifo.v \
ASIC/srcv/ss/platform/uart/uart_rx_fifo.v \
ASIC/srcv/ss/platform/uart/uart_brg.v \
ASIC/srcv/ss/platform/uart/uart_reg_ctrl.v \
ASIC/srcv/ss/platform/uart/uart_top.v \
ASIC/srcv/common/sequans_library/common.v \
ASIC/srcv/common/platform/ahbSlave/apb_smpi.v \
ASIC/srcv/common/sequans_library/regfile.v \
ASIC/srcv/common/sequans_library/sync_fifo.v \
ASIC/srcv/common/sequans_library/fifoctl_semi_sync/fifo_semi_sync_rctl.v \
ASIC/srcv/common/sequans_library/fifoctl_semi_sync/fifo_semi_sync_wctl.v \
ASIC/srcv/common/sequans_library/fifoctl_semi_sync/fifoctl_semi_sync.v \
ASIC/srcv/common/sequans_library/semi_sync_fifo_regfile.v \
ASIC/srcv/common/platform/ahbSlave/ahbBurstConvert.v \
ASIC/srcv/common/platform/ahbSlave/ahbSlave2FifoNoBurst.v \
ASIC/srcv/common/platform/ahbSlave/apb_ahb_slave.v \
ASIC/srcv/common/sequans_library/common.v \
ASIC/srcv/common/sequans_library/SQN_LOCAL_GC.v \
ASIC/srcv/common/config_regs/apbIf_timer_defs.v \
ASIC/srcv/common/config_regs/apbIf_timer.v \
ASIC/srcv/common/platform/apb/timer/timer_cnt.v \
ASIC/srcv/common/platform/apb/timer/apb_timer.v \
ASIC/srcv/common/sequans_library/common.v \
ASIC/srcv/common/sequans_library/SQN_LOCAL_GC.v \
ASIC/srcv/common/config_regs/apbIf_wdt_defs.v \
ASIC/srcv/common/config_regs/apbIf_wdt.v \
ASIC/srcv/common/platform/apb/wdt/wdt_cnt.v \
ASIC/srcv/common/platform/apb/wdt/apb_wdt.v \
ASIC/srcv/common/sequans_library/common.v \
ASIC/srcv/common/sequans_library/regfile.v \
ASIC/srcv/common/sequans_library/semi_sync_fifo.v \
ASIC/srcv/common/platform/ahbSlave/ext_ahbSlave2Fifo.v \
ASIC/srcv/common/sequans_library/regfile.v \
ASIC/srcv/common/platform/sdram_controller/sdram_controller.v \
ASIC/srcv/common/platform/sdram_controller/sdram_if.v \
ASIC/srcv/common/platform/sdram_controller/sdram_counters.v \
ASIC/srcv/common/platform/sdram_controller/sdram_addr_decode.v \
ASIC/srcv/common/platform/sdram_controller/sdram_wcmd_fifo.v \
ASIC/srcv/common/config_regs/sdramcfg_defs.v \
ASIC/srcv/common/config_regs/sdramcfg.v \
ASIC/srcv/common/platform/spi_ctrl/ahb_mem_spi.v \
ASIC/srcv/common/platform/spi_ctrl/spi_ctrl.v \
ASIC/srcv/common/config_regs/SPI_CFG_defs.v \
ASIC/srcv/common/config_regs/SPI_CFG.v \
ASIC/srcv/common/platform/dw_fifo2ahb.v \
ASIC/srcv/common/sequans_library/sync_fifo.v \
ASIC/srcv/common/sequans_library/common.v \
ASIC/srcv/common/platform/ahbSlave/phy_smpi.v \
ASIC/srcv/common/sequans_library/regfile.v \
ASIC/srcv/common/sequans_library/sync_fifo.v \
ASIC/srcv/common/sequans_library/fifoctl_semi_sync/fifo_semi_sync_rctl.v \
ASIC/srcv/common/sequans_library/fifoctl_semi_sync/fifo_semi_sync_wctl.v \
ASIC/srcv/common/sequans_library/fifoctl_semi_sync/fifoctl_semi_sync.v \
ASIC/srcv/common/sequans_library/semi_sync_fifo_regfile.v \
ASIC/srcv/common/platform/ahbSlave/ahbSlave2FifoNoBurst.v \
ASIC/srcv/common/platform/ahbSlave/phy_ahb_slave.v \
ASIC/srcv/common/sequans_library/common.v \
ASIC/srcv/common/platform/ahbSlave/mac_smpi.v \
ASIC/srcv/common/sequans_library/regfile.v \
ASIC/srcv/common/sequans_library/sync_fifo.v \
ASIC/srcv/common/sequans_library/fifoctl_semi_sync/fifo_semi_sync_rctl.v \
ASIC/srcv/common/sequans_library/fifoctl_semi_sync/fifo_semi_sync_wctl.v \
ASIC/srcv/common/sequans_library/fifoctl_semi_sync/fifoctl_semi_sync.v \
ASIC/srcv/common/sequans_library/semi_sync_fifo_regfile.v \
ASIC/srcv/common/platform/ahbSlave/ahbSlave2FifoNoBurst.v \
ASIC/srcv/common/platform/ahbSlave/mac_ahb_slave.v \
ASIC/srcv/ss/platform/usim/usimip/SciApbif.v \
ASIC/srcv/ss/platform/usim/usimip/SciTest.v \
ASIC/srcv/ss/platform/usim/usimip/SciRegBlk.v \
ASIC/srcv/ss/platform/usim/usimip/SciRegBlkUpdate.v \
ASIC/srcv/ss/platform/usim/usimip/SciTxFCntl.v \
ASIC/srcv/ss/platform/usim/usimip/SciTxRegFile.v \
ASIC/srcv/ss/platform/usim/usimip/SciTxFIFO.v \
ASIC/srcv/ss/platform/usim/usimip/SciRxRegFile.v \
ASIC/srcv/ss/platform/usim/usimip/SciRxFCntl.v \
ASIC/srcv/ss/platform/usim/usimip/SciRxFIFO.v \
ASIC/srcv/ss/platform/usim/usimip/SciSynctoPCLK.v \
ASIC/srcv/ss/platform/usim/usimip/SciSynctoSCICLK.v \
ASIC/srcv/ss/platform/usim/usimip/SciTxRx.v \
ASIC/srcv/ss/platform/usim/usimip/SciCntl.v \
ASIC/srcv/ss/platform/usim/usimip/SciDMA.v \
ASIC/srcv/ss/platform/usim/usimip/SciIntGen.v \
ASIC/srcv/ss/platform/usim/usimip/SciRevAnd.v \
ASIC/srcv/ss/platform/usim/usimip/Sci.v \
ASIC/srcv/ss/platform/usim/usim.v \
ASIC/srcv/ss/platform/sqn_itctl/itext_handler.v \
ASIC/srcv/ss/platform/sqn_itctl/sqn_itctl.v \
ASIC/srcv/common/config_regs/cfgitctl_defs.v \
ASIC/srcv/common/config_regs/cfgitctl.v \
ASIC/srcv/common/config_regs/gregs_host_defs.v \
ASIC/srcv/common/config_regs/gregs_host.v \
ASIC/srcv/common/config_regs/gregs_soc_defs.v \
ASIC/srcv/common/config_regs/gregs_soc.v \
ASIC/srcv/common/config_regs/gregs_soc_wcpu_defs.v \
ASIC/srcv/common/config_regs/gregs_soc_wcpu.v \
ASIC/srcv/common/sequans_library/clkchange_bit.v \
ASIC/srcv/ss/platform/cs_decoder.v \
ASIC/srcv/ss/platform/apbcs_decoder.v \
ASIC/srcv/ss/platform/gregs_wrapper.v \
ASIC/srcv/common/sequans_library/rst_bypass.v \
ASIC/srcv/ss/platform/ss_reset_gen.v \
ASIC/srcv/ss/platform/ss_platform.v \
ASIC/srcv/common/sequans_library/common.v \
ASIC/srcv/common/platform/ahb_mem.v \
ASIC/srcv/common/config_regs/cfgdma_defs.v \
ASIC/srcv/common/config_regs/cfgdma.v \
ASIC/srcv/common/mac/crc.v \
ASIC/srcv/ss/platform/dma_ctrl/dmar.v \
ASIC/srcv/ss/platform/dma_ctrl/dmaw.v \
ASIC/srcv/ss/platform/dma_ctrl/dma_ctrl.v \
ASIC/srcv/common/sequans_library/common.v \
ASIC/srcv/common/sequans_library/regfile.v \
ASIC/srcv/common/sequans_library/sync_fifo.v \
ASIC/srcv/common/platform/ahbMstr/rd_dphase.v \
ASIC/srcv/common/platform/ahbMstr/wr_dphase.v \
ASIC/srcv/common/platform/ahbMstr/mmpi.v \
ASIC/srcv/common/platform/ahbMstr/ahbMstr2Fifo.v \
ASIC/srcv/common/platform/ahbMstr/ahbMstrSyncRdWr.v \
ASIC/srcv/common/sequans_library/common.v \
ASIC/srcv/common/sequans_library/regfile.v \
ASIC/srcv/common/sequans_library/sync_fifo.v \
ASIC/srcv/common/platform/ahbMstr/rd_dphase.v \
ASIC/srcv/common/platform/ahbMstr/wr_dphase.v \
ASIC/srcv/common/platform/ahbMstr/mmpi.v \
ASIC/srcv/common/platform/ahbMstr/ahbMstr2Fifo.v \
ASIC/srcv/common/platform/ahbMstr/ahbMstrSyncRd.v \
ASIC/srcv/ss/platform/dma_ctrl/l2updater.v \
ASIC/srcv/ss/platform/dma_ctrl/l234parser.v \
ASIC/srcv/common/sequans_library/rst_bypass.v \
ASIC/srcv/common/sequans_library/common.v \
ASIC/srcv/common/sequans_library/regfile.v \
ASIC/srcv/common/sequans_library/sync_fifo.v \
ASIC/srcv/common/sequans_library/mux_1hot.v \
ASIC/srcv/common/sequans_library/mux_1hot_dflt.v \
ASIC/srcv/common/platform/marbiter/marbiter.v \
ASIC/srcv/common/platform/prio_shifter.v \
ASIC/srcv/common/sequans_library/common.v \
ASIC/srcv/common/sequans_library/rst_bypass.v \
ASIC/srcv/common/sequans_library/regfile.v \
ASIC/srcv/common/sequans_library/sync_fifo.v \
ASIC/srcv/common/sequans_library/fifoctl_semi_sync/fifo_semi_sync_rctl.v \
ASIC/srcv/common/sequans_library/fifoctl_semi_sync/fifo_semi_sync_wctl.v \
ASIC/srcv/common/sequans_library/fifoctl_semi_sync/fifoctl_semi_sync.v \
ASIC/srcv/common/sequans_library/semi_sync_fifo_regfile.v \
ASIC/srcv/common/sequans_library/clkchange_bit.v \
ASIC/srcv/common/platform/ahbMstr/rd_dphase.v \
ASIC/srcv/common/platform/ahbMstr/wr_dphase.v \
ASIC/srcv/common/platform/ahbMstr/mmpi.v \
ASIC/srcv/common/platform/ahbMstr/ahbMstr2Fifo.v \
ASIC/srcv/common/platform/ahbMstr/ahbMstr.v \
ASIC/srcv/ss/mac/receiver/ss_p2m_ofc.sv \
ASIC/srcv/ss/mac/receiver/ss_mhc.sv \
ASIC/srcv/common/mac/hcs.v \
ASIC/srcv/common/mac/crc.v \
ASIC/srcv/common/mac/crc32.v \
ASIC/srcv/common/sequans_library/countBlockAtMax.v \
ASIC/srcv/common/sequans_library/SQN_LOCAL_GC.v \
ASIC/srcv/common/mac/include/aes_std_defs.v \
ASIC/srcv/common/mac/include/aes_def.v \
ASIC/srcv/common/mac/aes/aes_rx.sv \
ASIC/srcv/common/mac/aes/aes_tx.sv \
ASIC/srcv/common/mac/aes/ext_aes.v \
ASIC/srcv/common/mac/aes/ext_aes_frame_analyzer.v \
ASIC/srcv/common/mac/aes/ext_aes_frame_modifier.v \
ASIC/srcv/common/mac/aes/aes_core.v \
ASIC/srcv/common/mac/aes/aes_fsm.v \
ASIC/srcv/common/mac/aes/aes_get_key.v \
ASIC/srcv/common/mac/aes/aes_sync_fifo.v \
ASIC/srcv/common/mac/aes/aes_regfile.v \
ASIC/srcv/common/mac/aes_helion/aes_standard_128only_roundkey.v \
ASIC/srcv/common/mac/aes_helion/aes_standard_encryptor.v \
ASIC/srcv/common/mac/aes_helion/aes_std_ccm_48cyc.v \
ASIC/srcv/common/mac/aes_helion/generic_std_enc_datapath.v \
ASIC/srcv/common/mac/aes_helion/generic_std_enc_logic.v \
ASIC/srcv/common/mac/aes_helion/generic_std_enc_lut.v \
ASIC/srcv/common/mac/aes_helion/generic_std_rk128_datapath.v \
ASIC/srcv/common/mac/aes_helion/generic_std_rk_lut.v \
ASIC/srcv/common/mac/aes_helion/generic_std_sbox_lut_module.v \
+incdir+ASIC/srcv/common/mac/include \
+incdir+ASIC/srcv/common/mac/aes_helion \
ASIC/srcv/ss/mac/receiver/ss_upc.sv \
ASIC/srcv/ss/mac/receiver/ss_udmc.sv \
ASIC/srcv/ss/mac/receiver/ss_top_mac_rx.v \
ASIC/srcv/common/mac/hcs.v \
ASIC/srcv/common/mac/crc.v \
ASIC/srcv/common/mac/crc16.v \
ASIC/srcv/common/mac/crc32.v \
ASIC/srcv/common/mac/transmitter/dcpc.sv \
ASIC/srcv/common/mac/transmitter/mci.sv \
ASIC/srcv/common/mac/transmitter/mhu.sv \
ASIC/srcv/common/mac/transmitter/sti.sv \
ASIC/srcv/common/mac/transmitter/hci.sv \
ASIC/srcv/common/mac/transmitter/m2p_ifc.v \
ASIC/srcv/common/sequans_library/SQN_LOCAL_GC.v \
ASIC/srcv/common/mac/include/aes_std_defs.v \
ASIC/srcv/common/mac/include/aes_def.v \
ASIC/srcv/common/mac/aes/aes_rx.sv \
ASIC/srcv/common/mac/aes/aes_tx.sv \
ASIC/srcv/common/mac/aes/ext_aes.v \
ASIC/srcv/common/mac/aes/ext_aes_frame_analyzer.v \
ASIC/srcv/common/mac/aes/ext_aes_frame_modifier.v \
ASIC/srcv/common/mac/aes/aes_core.v \
ASIC/srcv/common/mac/aes/aes_fsm.v \
ASIC/srcv/common/mac/aes/aes_get_key.v \
ASIC/srcv/common/mac/aes/aes_sync_fifo.v \
ASIC/srcv/common/mac/aes/aes_regfile.v \
ASIC/srcv/common/mac/aes_helion/aes_standard_128only_roundkey.v \
ASIC/srcv/common/mac/aes_helion/aes_standard_encryptor.v \
ASIC/srcv/common/mac/aes_helion/aes_std_ccm_48cyc.v \
ASIC/srcv/common/mac/aes_helion/generic_std_enc_datapath.v \
ASIC/srcv/common/mac/aes_helion/generic_std_enc_logic.v \
ASIC/srcv/common/mac/aes_helion/generic_std_enc_lut.v \
ASIC/srcv/common/mac/aes_helion/generic_std_rk128_datapath.v \
ASIC/srcv/common/mac/aes_helion/generic_std_rk_lut.v \
ASIC/srcv/common/mac/aes_helion/generic_std_sbox_lut_module.v \
+incdir+ASIC/srcv/common/mac/include \
+incdir+ASIC/srcv/common/mac/aes_helion \
ASIC/srcv/common/mac/transmitter/top_mac_tx.v \
ASIC/srcv/common/sequans_library/common.v \
ASIC/srcv/ss/mac/sram_interface/ss_contextCtrl.v \
ASIC/srcv/common/mac/sram_interface/aesCtrl.v \
ASIC/srcv/common/mac/sram_interface/aesCtrl_rx.v \
ASIC/srcv/common/sequans_library/sync_fifo.v \
ASIC/srcv/common/sequans_library/regfile.v \
ASIC/srcv/common/sequans_library/mux_1hot.v \
ASIC/srcv/ss/mac/sram_interface/sriGrant5.v \
ASIC/srcv/common/mac/sram_interface/sram_interface.v \
ASIC/srcv/ss/mac/sram_interface/ss_top_sram_interface.v \
ASIC/srcv/common/sequans_library/fifoInterrupts.v \
ASIC/srcv/common/sequans_library/countBlockAtMax.v \
ASIC/srcv/common/config_regs/cfgfifomac_defs.v \
ASIC/srcv/common/config_regs/cfgmac_defs.v \
ASIC/srcv/common/config_regs/cfgfifomac.v	 \
ASIC/srcv/common/config_regs/cfgmac.v	 \
ASIC/srcv/ss/mac/ss_top_mac.v \
ASIC/srcv/common/platform/ahb2_extahb.v \
ASIC/srcv/ss/arm946/ARM946Config/yoda/verilog/ARM946ES.v \
ASIC/srcv/common/config_regs/cfglpctrl_defs.v \
ASIC/srcv/common/config_regs/cfglpctrl.v \
ASIC/srcv/common/sequans_library/SQN_BUF.v \
ASIC/srcv/common/sequans_library/SQN_BUF_BUS.v \
ASIC/srcv/ss/tops/ss_top_mac_platform/lpctrl.v \
ASIC/srcv/ss/tops/ss_top_mac_platform/ss_top_mac_platform.v \
ASIC/srcv/ss/tops/sqn_top/arm_syncjtag.v \
"

for i in $files; do
  ~/bin/vapi.sh $i
done

